### PR TITLE
Update language server, and take some updates from the upstream repo

### PR DESCRIPTION
**Pull request by davidroeca**
Note that I updated the prettier config to be more similar to the one in https://github.com/sveltejs/language-tools so that it will be easy to bring in more patches as that repo gets more actively developed.

Closes: https://github.com/coc-extensions/coc-svelte/issues/1
Closes: https://github.com/coc-extensions/coc-svelte/issues/4
Closes: https://github.com/coc-extensions/coc-svelte/issues/5

### CODE REVIEW

**Comment by davidroeca** [comment]
currently broken. will update when fixed

**Comment by davidroeca** [comment]
there was an issue with the engine; should be functional now

**Comment by davidroeca** [comment]
For [vim-plug](https://github.com/junegunn/vim-plug) it would be:

```vim
Plug 'davidroeca/coc-svelte', { 'do': 'yarn install --frozen-lockfile && yarn build' }
```

For other plugin managers, something similar

**Comment by kanmii** [comment]
Hi @davidroeca 
Thanks for this pull request. I installed the extension directly from your repo.

How you get it working with `typescript`? I can get `svelte` to work in `vscode` using the instructions from this [blog post](https://dev.to/mhaecker/use-typescript-with-svelte-sapper-45n8), but same would not work with `coc-svelte`.

Your help will be highly appreciated.

**Comment by davidroeca** [comment]
@kanmii try [this doc](https://github.com/davidroeca/coc-svelte/blob/master/docs/preprocessors/typescript.md). If it's still not working, it would help me to see an example reproduction

**Comment by kanmii** [comment]
Whao! Thanks @davidroeca. Works like a charm with the template pointed to in the doc file. I will try to make it work with a sapper project I'm working on.

Make it a great weekend!
Thanks

**Comment by iamcco** [comment]
Sorry for the late reply, great work!!

**Comment by orta** [comment]
Anyone here is welcome to pop into the svelte language-tools chat room [on discord](https://svelte.dev/chat) if you want to chat with the folks working on the LSP too, nice work all

**Comment by davidroeca** [comment]
Sounds good! Happy to hop in on the discussion

**Comment by johnnynia** [comment]
This still hasn't been published or has it? I've also noticed a [seemingly more active fork](https://github.com/jjrdn/coc-svelte) published on npmjs.com as [coc-svelte-fork](https://www.npmjs.com/package/coc-svelte-fork) by @jjrdn. And @davidroeca proposed helping to maintain this repo on Discord. Would it be someshow possible to merge and synergize these efforts? 

Just asking after having struggled with my vim svelte setup for the last couple days 😅

**Comment by davidroeca** [comment]
@johnnynia have you had issues using this? Open an issue if so, or request an update. I do not use svelte actively enough yet to know when things really need to be updated. The language-tools repo is incredibly active so it’s hard to keep up especially since this isn’t part of that monorepo. I am still open to moving it in and that would make this a bit easier to maintain, though there are a few key difference in how much is supported in coc/vim and in vscods (syntax highlighting, for example, is supported in the vscode plugin but not here).

I had set up a fork for myself a while back but I opened a pull request here so that I could contribute back to the coc/vim community. I hope that another person who decides to maintain a fork will also consider this too.

Personally I am unclear why this would need to be published to npm, since you don’t need it on npm to use it or install it with coc. Is there a particular use case I am missing here?

**Comment by johnnynia** [comment]
@davidroeca Thanks for your reply! You're right, it does not have to be published on npm (just tested it on a coworker's computer). Somehow coc would not update the extension to the last version what let me to the wrong assumption that it needs to be published, and therefore I've installed it via Plug. So no issue here :-)

I share your hopes regarding joining contribution efforts in order to keep up with the pace in language-tools repo. Unfortunately I'm not yet too familiar with coc (as I have just proven 😅).

**Comment by iamcco** [comment]
@davidroeca it had been published to npm after merged. I'm also not use svelte actively enough to tracking upstream since my work turn to use angular.

**Pull request merged**
